pool:
    vmImage: windows-2019

steps:
  - checkout: self
    fetchDepth: 1
    displayName: Checkout ACE3

  - powershell: |
      mkdir C:\build\x
      git clone --depth 1 https://github.com/CBATeam/CBA_A3.git C:\build\x\cba
    displayName: Checkout CBA A3

  - powershell: docker pull dahlgren/arma3tools:python
    displayName: Download Arma 3 tools image

  - task: DownloadPipelineArtifact@2
    displayName: Download Arma 3 tools
    inputs:
      buildType: specific
      project: e7eb96e8-c73f-4620-8dec-23e1895db846
      definition: 2
      runVersion: latestFromBranch
      runBranch: refs/heads/master
      artifactName: tools
      targetPath: C:\arma3tools

  - task: DownloadPipelineArtifact@2
    displayName: Download Arma 3 data
    inputs:
      buildType: specific
      project: e7eb96e8-c73f-4620-8dec-23e1895db846
      definition: 2
      runVersion: latestFromBranch
      runBranch: refs/heads/master
      artifactName: arma3
      targetPath: C:\build

  - task: DownloadPipelineArtifact@2
    displayName: Download RHS AFRF
    inputs:
      buildType: specific
      project: e7eb96e8-c73f-4620-8dec-23e1895db846
      definition: 1
      runVersion: latestFromBranch
      runBranch: refs/heads/master
      artifactName: rhsafrf
      targetPath: C:\build

  - task: DownloadPipelineArtifact@2
    displayName: Download RHS GREF
    inputs:
      buildType: specific
      project: e7eb96e8-c73f-4620-8dec-23e1895db846
      definition: 1
      runVersion: latestFromBranch
      runBranch: refs/heads/master
      artifactName: rhsgref
      targetPath: C:\build

  - task: DownloadPipelineArtifact@2
    displayName: Download RHS SAF
    inputs:
      buildType: specific
      project: e7eb96e8-c73f-4620-8dec-23e1895db846
      definition: 1
      runVersion: latestFromBranch
      runBranch: refs/heads/master
      artifactName: rhssaf
      targetPath: C:\build

  - task: DownloadPipelineArtifact@2
    displayName: Download RHS USAF
    inputs:
      buildType: specific
      project: e7eb96e8-c73f-4620-8dec-23e1895db846
      definition: 1
      runVersion: latestFromBranch
      runBranch: refs/heads/master
      artifactName: rhsusf
      targetPath: C:\build

  - powershell: |
      New-Item C:\build\build.cmd
      Set-Content C:\build\build.cmd 'pboproject -P & subst P: C:\build && py P:\z\ace\tools\make.py ci'
      xcopy /e /h $(Build.SourcesDirectory)\tools\pDummies\A3\ui_f_enoch C:\build\a3\ui_f_enoch\
    displayName: Setup environment

  - powershell:
      docker run
      -e PYTHONUNBUFFERED=1
      -v C:\arma3tools:C:\arma3tools
      -v C:\build:C:\build
      -v $(Build.SourcesDirectory):C:\build\z\ace
      dahlgren/arma3tools:python
      C:\build\build.cmd
    displayName: Build

  - powershell: |
     mkdir C:\build\logs
     copy C:\build\temp\*.log C:\build\logs
    displayName: Copy logs
    condition: succeededOrFailed()

  - task: PublishPipelineArtifact@1
    displayName: Publish build logs
    inputs:
      targetPath: C:\build\logs
      artifact: logs
    condition: succeededOrFailed()

  - task: PublishPipelineArtifact@1
    displayName: Publish @ace
    inputs:
      targetPath: $(Build.SourcesDirectory)\release\@ace
      artifact: '@ace'
    condition: succeededOrFailed()
