name: HEMTT

on:
  push:
    branches:
    - master
  pull_request_target:

jobs:
  windows:
    runs-on: windows-latest
    steps:
    - name: Install Arma 3 Tools
      uses: arma-actions/arma3-tools@master
      with:
        toolsUrl: ${{ secrets.ARMA3_TOOLS_URL }}
    - name: Checkout the source code
      uses: actions/checkout@v4
    - name: Setup HEMTT
      uses: arma-actions/hemtt@v1
    - name: Run HEMTT build
      run: hemtt build
    - name: Rename build folder
      run: mv .hemttout/build .hemttout/@ace
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: ace3-${{ github.sha }}
        path: .hemttout/@*
